author: antigravity
description: 'Automate WhatsApp Business tasks via Rube MCP (Composio): send messages,
  manage templates, upload media, and handle contacts. Always search tools first for
  current schemas.'
domain: uncategorized
id: whatsapp-automation
name: whatsapp-automation
triggers:
  keywords:
  - whatsapp
  - automation
  - whatsapp automation
  - automate
  - business
  - tasks
  - rube
  - composio
  - send
  - messages
type: knowledge
version: '1.0'
